[build]
  command = "npm ci && ./node_modules/.bin/tsc --noEmit && vite build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  CI = "true"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["cheerio"]

[dev]
  framework = "vite"
  targetPort = 5173
  port = 8888
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200