[build]
  command = "npm ci && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NODE_ENV = "production"
  CI = "true"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["cheerio"]
  included_files = ["src/types/**", "src/utils/**"]

[dev]
  framework = "vite"
  targetPort = 5173
  port = 8888
  publish = "dist"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200