[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  CI = "true"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["cheerio"]

[dev]
  framework = "vite"
  targetPort = 5173
  port = 8888
  publish = "dist"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
    Cache-Control = "public, max-age=0, must-revalidate"
    Content-Security-Policy = """
      default-src 'self' *.netlify.app;
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://static.cloudflareinsights.com;
      style-src 'self' 'unsafe-inline';
      font-src 'self' data: https://fonts.gstatic.com;
      img-src 'self' data: https: blob:;
      connect-src 'self' *.netlify.app https://*.netlify.app/.netlify/functions/* https://static.cloudflareinsights.com;
      frame-src 'none';
      object-src 'none';
      base-uri 'self';
      form-action 'self';
      frame-ancestors 'none';
      upgrade-insecure-requests;
    """