[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  CI = "true"
  NODE_ENV = "production"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["cheerio"]

[dev]
  framework = "vite"
  targetPort = 5173
  port = 8888
  publish = "dist"